# yaml-language-server: $schema=https://raw.githubusercontent.com/Ledger-Donjon/laserstudio/main/laserstudio/config_schema/config.schema.json
camera:
  enable: true
  label: "Dinolite"
  type: USB
  refresh_interval_ms: 50
  index: 0
stage:
  enable: true
  label: "CNC Router 3018"
  refresh_interval_ms: 100
  type: CNC
  dev:
    vid: "1A86"
    pid: "7523"
  unit_factor: 1000
probes:
  - enable: true
    label: "SiliconToaster"
