# yaml-language-server: $schema=https://raw.githubusercontent.com/Ledger-Donjon/laserstudio/main/laserstudio/config_schema/config.schema.json
camera:
  dev: /dev/ttySPIXCI0
  pixel_size_in_um: [14.84375, 14.84375]
  type: Raptor
  objective: 20.0
  objectives: [5, 10, 20, 50]
  refresh_interval_ms: 10
  label: Raptor
  invert_vertical: true
  index: 0

focus:
  coarse:
    span: 1600
    steps: 20
    averaging: 5
    multi_peaks: true
    best_is_highest_z: false
  fine:
    span: 500
    steps: 20
    averaging: 10
    multi_peaks: true
    best_is_highest_z: false
  autofocus_points:
    - [-20582.34, 25125.61, -11517.5]
    - [-18798.77, 25230.96, -11534.15]
    - [-18823.239999999998, 23840.82, -11535.35]

stage:
  dev:
    sn: 11PCOA5!
  label: PI Mercury
  adresses: [1, 2, 3]
  type: PI
  unit_factors: [-1000.0, 1000.0, -1000.0]
  guardrail_um: 90000.0
  refresh_interval_ms: 20
  shear: [0.000, 0.000]

lighting:
  dev:
    sn: A10R257S
  motor: 1
  type: LMSController
  label: LMS Lighting
  open_is_slidein: false

lasers:
  - type: PDM
    label: PDM 980nm
    enable: true
    num: 2
    refresh_interval_ms: 1000
    dev:
      sn: FTA6L8GZ
    shutter:
      dev:
        sn: A10R257S
      motor: 2
      type: LMSController
      label: LMS Laser
