# yaml-language-server: $schema=https://raw.githubusercontent.com/Ledger-Donjon/laserstudio/main/laserstudio/config_schema/config.schema.json
camera:
  enable: true
  label: Front side Camera
  type: USB
  refresh_interval_ms: 50
  index: 0
  objective: 5.0
  objectives: [1, 5, 10, 20, 50]
  pixel_size_in_um: [15, 15]
  invert_vertical: false
stage:
  enable: true
  label: Dummy stage
  refresh_interval_ms: 100
  type: Dummy
  unit_factor: 1000
  num_axis: 3
lasers:
- enable: true
  label: Dummy Laser
  type: Dummy
  spot_size_um: 20.0
probes:
- enable: true
  label: Dummy Probe
  spot_size_um: 20.0
